# -*- coding: utf-8 -*-
# Copyright (c) Streamlit Inc. (2018-2022) Snowflake Inc. (2022-2025)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streamlit/proto/Metric.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from streamlit.proto import LabelVisibilityMessage_pb2 as streamlit_dot_proto_dot_LabelVisibilityMessage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cstreamlit/proto/Metric.proto\x1a,streamlit/proto/LabelVisibilityMessage.proto\"\x9b\x03\n\x06Metric\x12\r\n\x05label\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t\x12\r\n\x05\x64\x65lta\x18\x03 \x01(\t\x12*\n\tdirection\x18\x04 \x01(\x0e\x32\x17.Metric.MetricDirection\x12\"\n\x05\x63olor\x18\x05 \x01(\x0e\x32\x13.Metric.MetricColor\x12\x0c\n\x04help\x18\x06 \x01(\t\x12\x31\n\x10label_visibility\x18\x07 \x01(\x0b\x32\x17.LabelVisibilityMessage\x12\x13\n\x0bshow_border\x18\x08 \x01(\x08\x12\x12\n\nchart_data\x18\t \x03(\x01\x12%\n\nchart_type\x18\n \x01(\x0e\x32\x11.Metric.ChartType\"-\n\x0fMetricDirection\x12\x08\n\x04\x44OWN\x10\x00\x12\x06\n\x02UP\x10\x01\x12\x08\n\x04NONE\x10\x02\"+\n\x0bMetricColor\x12\x07\n\x03RED\x10\x00\x12\t\n\x05GREEN\x10\x01\x12\x08\n\x04GRAY\x10\x02\"(\n\tChartType\x12\x08\n\x04LINE\x10\x00\x12\x07\n\x03\x42\x41R\x10\x01\x12\x08\n\x04\x41REA\x10\x02\x42+\n\x1c\x63om.snowflake.apps.streamlitB\x0bMetricProtob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streamlit.proto.Metric_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034com.snowflake.apps.streamlitB\013MetricProto'
  _METRIC._serialized_start=79
  _METRIC._serialized_end=490
  _METRIC_METRICDIRECTION._serialized_start=358
  _METRIC_METRICDIRECTION._serialized_end=403
  _METRIC_METRICCOLOR._serialized_start=405
  _METRIC_METRICCOLOR._serialized_end=448
  _METRIC_CHARTTYPE._serialized_start=450
  _METRIC_CHARTTYPE._serialized_end=490
# @@protoc_insertion_point(module_scope)
